require("config.plugins.telescope")
require("config.plugins.treesitter")
require("config.plugins.lsp")
require("config.plugins.autocompletion")
require("config.plugins.whichkey")
require("config.plugins.tree")
